name: PSI 
target_size: &target_size !!python/tuple [128, 128]
dbatch_size: &dbatch_size 1
checkpoint_path: &checkpoint_path ./weights/fast_mri/sota/
#
# Experiment
#
experiment:
  name: 23_RA_MIDL
  task: train
  weights: #'./weights/fast_mri/sota/2023_08_30_07_46_29_308852/best_model.pt'
#
device: gpu
configurator:
  module_name: core.Configurator
  class_name: DLConfigurator
  params:
#
# Model
#
model:
  module_name: model_zoo.psi
  class_name: PSI
  params:
    cdim: 1
    zdim: 128
    channels:
      - 64
      - 128
      - 256
      - 512
      - 512
    image_size: 128
    conditional: False
    
#
# Trainer default hyperparam for losses
#  self.content_weight = 1e5
#         # self.style_weight = 3e4
#         # self.tv_weight = 1e0
#
trainer:
  module_name: projects.23_uad_review.PHITrainer
  class_name: PTrainer
  freeze_theta : True
  params:
    input_size: *target_size
    checkpoint_path: *checkpoint_path
    nr_epochs: 4000
    path_to_s2: 'data/fastMRI/splits/train_s2.csv'
    path_to_ra_weights: './full_train_s1/2023_10_31_20_31_15_687127/best_model.pt'
    # content_weight: 1e5
    # style_weight: 3e4
    content_weight: 1
    style_weight: 10
    encoder_name : 'EfficientNetB3'
    tv_weight: 0
    alfa: 1
    loss:
      module_name: optim.losses.ln_losses
      class_name: L2
      params:
    # Optimizer
    patience: 4000
    optimizer_params:
      lr: 5.0e-5 # 2.0e-4 $ orig
  # Data Loader
  data_loader:
# IXI-T1
    module_name: core.DataLoader
    class_name: DefaultDataLoader
    params:
      args:
        dataset_module:
          module_name: data.loaders.fastmri_loader
          class_name: FastLoader
        data_dir:
          train:
          - './data/fastMRI/splits/train_s1_split.csv'
          val:
          - './data/fastMRI/splits/val_s1_split.csv'
          test:
          - './data/fastMRI/splits/normal_test.csv'
        target_size: *target_size
        batch_size: 8
# Downstream tasks
downstream_tasks:
  detection_stroke:
    module_name: projects.23_uad_review.DownstreamEvaluatorAtlas
    # module_name: projects.23_uad_review.DownstreamEvaluator
    class_name: PDownstreamEvaluator
    checkpoint_path: *checkpoint_path
    global_detection: True
    data_loader:
      module_name: core.DataLoader
      class_name: DefaultDataLoader
      params:
        args:
          target_size: *target_size
          batch_size: *dbatch_size
          dataset_module:
            module_name: data.loaders.ixi_loader
            class_name: IXILoader
      datasets:
        Atlas:
          data_dir:
            test:
              - 'data/ATLAS/splits/atlas_train_png.csv'
          label_dir:
            test:
              - 'data/ATLAS/splits/atlas_train_mask_png.csv'
